2023-03-26 18:03:04 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 13956 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-26 18:03:04 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-26 18:03:04 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-26 18:03:06 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 2.078 seconds (JVM running for 3.092)
2023-03-26 18:03:15 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-26 18:03:18 INFO  PhoneBookController:41 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-26 18:03:18 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-26 18:03:20 INFO  PhoneBookController:41 - Вызвали метод addContact с переданным контактом: {0, 2, 2}
2023-03-26 18:03:20 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:55:45 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 16984 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 15:55:45 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 15:55:45 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 15:55:46 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.618 seconds (JVM running for 3.603)
2023-03-27 15:55:57 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:56:03 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:57:13 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:58:04 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:58:21 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 8480 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 15:58:21 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 15:58:21 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 15:58:23 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 2.879 seconds (JVM running for 3.775)
2023-03-27 15:58:24 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 15:58:26 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:02:36 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 15848 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 16:02:36 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 16:02:36 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 16:02:38 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 2.9 seconds (JVM running for 4.283)
2023-03-27 16:02:41 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:02:43 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:02:46 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:02:49 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:03:39 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 5212 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 16:03:39 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 16:03:39 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 16:03:42 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 3.029 seconds (JVM running for 4.449)
2023-03-27 16:03:43 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:03:43 ERROR PhoneBookController:31 - Список контактов пуст
2023-03-27 16:03:45 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:03:45 ERROR PhoneBookController:31 - Список контактов пуст
2023-03-27 16:07:38 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:07:38 ERROR PhoneBookController:31 - Список контактов пуст
2023-03-27 16:08:17 INFO  PhoneBookController:26 - Вызвали метод getAllContacts()
2023-03-27 16:08:17 ERROR PhoneBookController:31 - Список контактов пуст
2023-03-27 16:55:39 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 11416 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 16:55:39 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 16:55:39 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 16:55:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:40 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.445 seconds (JVM running for 2.136)
2023-03-27 16:55:45 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:49 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-27 16:55:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:51 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 2, 2}
2023-03-27 16:55:51 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:52 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 3, 3}
2023-03-27 16:55:52 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:55 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 4, 4}
2023-03-27 16:55:55 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:57 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 5, 5}
2023-03-27 16:55:57 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:55:58 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 6, 6}
2023-03-27 16:55:58 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:56:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:16 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 16332 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 16:57:16 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 16:57:16 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 16:57:17 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:17 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.384 seconds (JVM running for 2.079)
2023-03-27 16:57:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:23 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-27 16:57:23 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:25 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 2, 2}
2023-03-27 16:57:25 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:26 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 3, 3}
2023-03-27 16:57:26 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:27 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:28 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 4, 4}
2023-03-27 16:57:28 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:37 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:47 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 16:57:57 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:27 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 11800 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:02:27 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:02:27 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:02:28 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:28 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.429 seconds (JVM running for 2.107)
2023-03-27 17:02:28 INFO  PhoneBookController:84 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:02:37 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:38 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:38 INFO  PhoneBookController:84 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:02:38 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:39 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:42 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-27 17:02:42 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:44 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 2, 2}
2023-03-27 17:02:44 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:46 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 3, 3}
2023-03-27 17:02:46 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:48 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:48 INFO  PhoneBookController:84 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {4, 3, 3}
2023-03-27 17:02:58 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:02:58 INFO  PhoneBookController:84 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {3, 2, 2}
2023-03-27 17:13:46 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 5804 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:13:46 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:13:46 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:13:47 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:13:47 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.44 seconds (JVM running for 2.235)
2023-03-27 17:13:47 INFO  PhoneBookController:85 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:13:47 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:13:57 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:13:57 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:02 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:07 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:07 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:17 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:17 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:27 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:27 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:37 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:37 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:47 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:47 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:14:57 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:14:57 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:15:07 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:07 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:15:17 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:17 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:15:27 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:27 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:15:37 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:37 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:15:49 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 3664 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:15:49 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:15:49 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:15:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:50 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.417 seconds (JVM running for 2.082)
2023-03-27 17:15:50 INFO  PhoneBookController:85 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:15:50 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:15:54 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:55 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:15:59 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-27 17:15:59 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:00 INFO  PhoneBookController:85 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {2, 1, 1}
2023-03-27 17:16:00 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {2, 1, 1}
2023-03-27 17:16:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:16:14 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:16:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:16:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:16:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:16:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:17:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:17:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:18:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:18:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:19:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:19:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:20:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:20:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:21:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:21:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:20 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:30 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:40 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:40 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:22:50 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:22:50 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:00 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:00 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:10 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:17 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 10144 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:23:17 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:23:17 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:23:18 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:18 DEBUG PhoneBookController:84 - Random index: 0
2023-03-27 17:23:18 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.331 seconds (JVM running for 1.997)
2023-03-27 17:23:18 INFO  PhoneBookController:86 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:23:18 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:23:28 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:28 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:38 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:38 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:48 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:48 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:23:58 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:23:58 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:24:08 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:08 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:24:18 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:18 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:24:28 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 8608 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:24:28 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:24:28 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:24:29 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:29 DEBUG PhoneBookController:91 - Random index: 0
2023-03-27 17:24:29 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.327 seconds (JVM running for 2.013)
2023-03-27 17:24:29 INFO  PhoneBookController:93 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:24:29 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:24:39 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:39 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:24:39 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:24:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:49 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:24:49 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:24:59 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:24:59 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:24:59 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:09 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:09 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:09 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:19 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:19 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:19 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:29 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:29 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:29 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:39 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:39 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:39 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:49 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:49 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:25:59 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:25:59 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:25:59 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:09 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:09 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:09 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:19 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:19 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:19 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:29 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:29 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:29 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:39 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:39 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:39 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:49 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:49 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:26:59 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:26:59 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:26:59 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:27:09 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:09 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:27:09 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:27:19 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:19 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:27:19 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:27:37 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 8760 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:27:37 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:27:37 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:27:38 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:38 DEBUG PhoneBookController:91 - Random index: 2
2023-03-27 17:27:38 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.37 seconds (JVM running for 2.042)
2023-03-27 17:27:38 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {3, Вася, 9121116566}
2023-03-27 17:27:38 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {3, Вася, 9121116566}
2023-03-27 17:27:48 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:48 DEBUG PhoneBookController:91 - Random index: 1
2023-03-27 17:27:48 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {2, Петр, 9123456566}
2023-03-27 17:27:48 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {2, Петр, 9123456566}
2023-03-27 17:27:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:58 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:27:58 DEBUG PhoneBookController:91 - Random index: 0
2023-03-27 17:27:58 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:27:58 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:28:02 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:28:08 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:28:08 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:28:08 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:28:18 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:28:18 ERROR PhoneBookController:85 - Список контактов пуст, нечего удалять
2023-03-27 17:28:18 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
java.lang.RuntimeException: Список контактов пуст, нечего удалять
	at ru.yudina.springcourse.controllers.PhoneBookController.deleteRandomContactBySchedule(PhoneBookController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-27 17:30:02 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 4420 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:30:02 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:30:02 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:30:03 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:03 DEBUG PhoneBookController:91 - Random index: 2
2023-03-27 17:30:03 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.371 seconds (JVM running for 2.059)
2023-03-27 17:30:03 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {3, Вася, 9121116566}
2023-03-27 17:30:03 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {3, Вася, 9121116566}
2023-03-27 17:30:05 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:08 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 1, 1}
2023-03-27 17:30:08 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:10 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 2, 2}
2023-03-27 17:30:10 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:12 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 3, 3}
2023-03-27 17:30:12 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:13 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:13 DEBUG PhoneBookController:91 - Random index: 3
2023-03-27 17:30:13 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {5, 2, 2}
2023-03-27 17:30:13 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {5, 2, 2}
2023-03-27 17:30:14 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 4, 4}
2023-03-27 17:30:14 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:20 INFO  PhoneBookController:42 - Вызвали метод addContact с переданным контактом: {0, 5, 5}
2023-03-27 17:30:20 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:22 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {6, 3, 3}
2023-03-27 17:30:22 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:23 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:23 DEBUG PhoneBookController:91 - Random index: 4
2023-03-27 17:30:23 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {8, 5, 5}
2023-03-27 17:30:23 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {8, 5, 5}
2023-03-27 17:30:26 INFO  PhoneBookController:69 - Вызвали метод deleteCheckedContacts с переданными id контактов: [2, 4]
2023-03-27 17:30:26 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:28 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:30 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:31 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:31 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:32 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:33 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:33 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:30:33 DEBUG PhoneBookController:91 - Random index: 1
2023-03-27 17:30:33 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {7, 4, 4}
2023-03-27 17:30:33 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {7, 4, 4}
2023-03-27 17:30:33 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:32:40 INFO  SpringBootAppApplication:55 - Starting SpringBootAppApplication using Java 11.0.17 on LAPTOP-EFKQ41G8 with PID 2228 (C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot\target\classes started by anuta in C:\Users\anuta\IdeaProjectsLearn\anna-yudina-spring-boot)
2023-03-27 17:32:40 DEBUG SpringBootAppApplication:56 - Running with Spring Boot v2.7.9, Spring v5.3.25
2023-03-27 17:32:40 INFO  SpringBootAppApplication:631 - No active profile set, falling back to 1 default profile: "default"
2023-03-27 17:32:41 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:32:41 DEBUG PhoneBookController:91 - Random index: 0
2023-03-27 17:32:41 INFO  SpringBootAppApplication:61 - Started SpringBootAppApplication in 1.405 seconds (JVM running for 2.088)
2023-03-27 17:32:41 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {1, Иван, 9123456789}
2023-03-27 17:32:41 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {1, Иван, 9123456789}
2023-03-27 17:32:49 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:32:51 INFO  PhoneBookController:28 - Вызвали метод getAllContacts()
2023-03-27 17:32:51 DEBUG PhoneBookController:91 - Random index: 0
2023-03-27 17:32:51 INFO  PhoneBookController:94 - Вызвали метод deleteRandomContactBySchedule по расписанию, удаляемый контакт: {2, Петр, 9123456566}
2023-03-27 17:32:51 INFO  PhoneBookController:57 - Вызвали метод deleteContact с переданным контактом: {2, Петр, 9123456566}
